language: php
php:
- 5.5
- 5.6
- hhvm-nightly
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm-nightly
addons:
  postgresql: '9.3'
sudo: false
install:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
before_script:
  - psql -c 'create database test0;' -U postgres
  - psql -U postgres -c 'create extension postgis' -d test0
  - php app/console --env=test cache:warmup
  - php app/console doctrine:migrations:migrate --no-interaction
  - php app/console doctrine:fixtures:load --no-interaction --env=test
script: phpunit -c app/
notifications:
  email:
  - info@champs-libres.coop