wikipedale_notations:
    pattern:  /
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:index" }

wikipedale_notations_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:show" }

wikipedale_notations_new:
    pattern:  /new
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:new" }

wikipedale_notations_create:
    pattern:  /create
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:create" }
    requirements: { _method: post }

wikipedale_notations_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:edit" }

wikipedale_notations_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:update" }
    requirements: { _method: post }

wikipedale_notations_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProgracqteurWikipedaleBundle:Notation:delete" }
    requirements: { _method: post }
