imports:
    - { resource: parameters.yml}
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          
      resource: "%kernel.root_dir%/config/routing.yml" 
      strict_requirements: "%kernel.debug%"
    default_locale: "%locale%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
        - 'ProgracqteurWikipedaleBundle:Form:fields.html.twig'
    globals:
        date_format: %date_format%
        user_manuel_url: %user_manuel_url%
        contact_url: %contact_url%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles: []
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8  
          mapping_types:
            geography: point
            geometry: string
            hstore: string
            xml: hash
      types:
        file: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\FileType
        hash: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\HashType
        address: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\AddressType
        geometry:   CrEOF\Spatial\DBAL\Types\GeographyType
        point:      CrEOF\Spatial\DBAL\Types\Geography\PointType
        polygon:    CrEOF\Spatial\DBAL\Types\Geography\PolygonType
        linestring: CrEOF\Spatial\DBAL\Types\Geography\LineStringType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
          string_functions:
            covers: Progracqteur\WikipedaleBundle\Resources\Doctrine\Functions\Covers
            crosses: Progracqteur\WikipedaleBundle\Resources\Doctrine\Functions\Crosses
          numeric_functions:
            st_covers:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCovers
            st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
            st_distance:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
            st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
            st_length:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
            st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
        
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool: { type: memory }


 
 # FOSUserBundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Progracqteur\WikipedaleBundle\Entity\Management\User
    group:
      group_class: Progracqteur\WikipedaleBundle\Entity\Management\Group
    registration:
      confirmation:
        enabled: true
      form:
        type: wikipedale_user_registration
    profile:
      form:
        type: wikipedale_user_profile
    from_email:
      address: admin-wikipedale@fastre.info
      sender_name: admin-wikipedale

parameters:
    notifications_subscription_moderator_events: [100, 1050, 1060, 1070, 110, 120, 130, 135, 141, 160, 170, 180, 181, 190, 193, 198, 200, 210]
    notifications_subscription_moderator_service: "progracqteur.wikipedale.notification.filter.subscription_kind_moderator"
    notifications_subscription_manager_events: [100, 1050, 1060, 1070, 110, 120, 130, 135, 141, 160, 170, 180, 181, 190, 193, 198, 200, 210]
    notifications_subscription_manager_service: "progracqteur.wikipedale.notification.filter.subscription_kind_manager"
