imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8  
          mapping_types:
            geography: point
            xml: hash
        
      types:
        point: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\PointType
        file: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\FileType
        hash: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\HashType
        address: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\AddressType
        polygon: Progracqteur\WikipedaleBundle\Resources\Doctrine\Types\PolygonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
          string_functions:
            covers: Progracqteur\WikipedaleBundle\Resources\Doctrine\Functions\Covers

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
 
 # FOSUserBundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Progracqteur\WikipedaleBundle\Entity\Management\User
    group:
      group_class: Progracqteur\WikipedaleBundle\Entity\Management\Group
    registration:
      confirmation:
        enabled: true
      form:
        type: wikipedale_user_registration
    from_email:
      address: admin-wikipedale@fastre.info
      sender_name: admin-wikipedale
