

_assetic:
    resource: .
    type:     assetic

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
    
    #debogage: ces chemins seront supprimés par la suite ou rendu inaccessible
# en version de production

debug_one:
  pattern: /debug/one
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:debugOne }
  
debug_two:
  pattern: /debug/two
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:debugTwo }
  
dev_send_request:
  pattern: /dev/send_place
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:devSendPlace }
  
dev_test_token:
  pattern: /dev/test_token
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:devSendTestToken}
