security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_NOTATION, ROLE_CATEGORY, ROLE_MODERATOR, ROLE_SEE_USER_DETAILS, ROLE_PUBLISHED, ROLE_DETAILS_LITTLE, ROLE_DETAILS_BIG, ROLE_SEE_USER_DETAILS, ROLE_MANAGER_ALTER, ROLE_PLACETYPE_ALTER, ROLE_SEE_UNACCEPTED, ROLE_PLACE_TERM]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_MODERATOR: [ROLE_COMMENT_MODERATOR_MANAGER, ROLE_PLACE_TERM, ROLE_MODERATOR_ALTER]
        ROLE_MANAGER: [ROLE_COMMENT_MODERATOR_MANAGER]

    providers:
        fos_userbundle:
            id: fos_user.user_manager


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            wsse: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }