ProgracqteurWikipedaleBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ProgracqteurWikipedaleBundle:Default:index }
    
wikipedale_homepage:
  pattern: /
  defaults: {_controller: ProgracqteurWikipedaleBundle:Default:homepage }
  
wikipedale_to_city:
  pattern: /{city}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Manager:toCity }
  requirements:
    city: mons|liege
    
wikipedale_reset_city:
  pattern: /reset_city
  defaults: {_controller: ProgracqteurWikipedaleBundle:Manager:resetCity }
  
wikipedale_place_view:
  pattern: /place/view/{id}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Place:view }
  requirements:
    _format: html|json
    
wikipedale_place_list_by_bbox:
  pattern: /place/list/bybbox.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Place:listByBBox }
  requirements:
    _format: json
    
wikipedale_place_list_by_city:
  pattern: /place/list/bycity.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Place:listByCity }
  requirements:
    _format: json

wikipedale_place_change:
  pattern: /place/change.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Place:change }
  requirements:
    _format: json
    
    
wikipedale_photo_by_place:
  pattern: /photo/byplace/{placeId}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:getPhotoByPlace }
  requirements:
    _format: json|html
    
wikipedale_photo_new:
  pattern: /photo/new/place-{placeId}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:new }
  requirements:
    _format: html
    
wikipedale_photo_update:
  pattern: /photo/update/{photoId}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:update }
  requirements:
    _format: html

#debogage: ces chemins seront supprimés par la suite ou rendu inaccessible
# en version de production

debug_one:
  pattern: /debug/one
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:debugOne }
  
debug_two:
  pattern: /debug/two
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:debugTwo }
  
dev_send_request:
  pattern: /dev/send_place
  defaults: {_controller: ProgracqteurWikipedaleBundle:Debug:devSendPlace }
