ProgracqteurWikipedaleBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ProgracqteurWikipedaleBundle:Default:index }
    
wikipedale_homepage:
  pattern: /
  defaults: {_controller: ProgracqteurWikipedaleBundle:Default:homepage }
  
wikipedale_place_view:
  pattern: /place/view/{id}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Place:view }
  requirements:
    _format: html|json
    

