ProgracqteurWikipedaleBundle_admin_category:
  resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/category_admin.yml"
  prefix:   /admin/category

ProgracqteurWikipedaleBundle_public_category:
  resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/category_public.yml"
  prefix:   /category

ProgracqteurWikipedaleBundle_zone:
  resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/zone_public.yml"
  prefix:   /zone
  
ProgracqteurWikipedaleBundle_admin_zone:
  resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/zone_admin.yml"
  prefix:   /admin/zone

ProgracqteurWikipedaleBundle_comment:
  resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/model_comment.yml"
  prefix:   /comment

wikipedale_notations:
    resource: "@ProgracqteurWikipedaleBundle/Resources/config/routing/management_notation.yml"
    prefix:   /admin/notation

wikipedale_homepage:
  pattern: /
  defaults: {_controller: ProgracqteurWikipedaleBundle:Main:homepage }
  options:
    expose: true

wikipedale_about:
    pattern:  /about
    defaults: { _controller: ProgracqteurWikipedaleBundle:Main:about }
    options:
      expose: true

wikipedale_zone_zoom_on:
  pattern: /zoom/on/{zoneSlug}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Zone:selectZoneForZoom }
  options:
    expose: true

wikipedale_reset_zone_selection:
  pattern: /reset/zone/selection
  defaults: {_controller: ProgracqteurWikipedaleBundle:Zone:resetZoneSelection }
  options:
    expose: true

wikipedale_report_view:
  pattern: /report/view/{id}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:view }
  requirements:
    _format: json

wikipedale_light_list:
  pattern: /report/light/list.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:lightList }
  requirements:
    _format: json
  options:
    expose: true

wikipedale_report_list_by_zone:
  pattern: /report/list/byzone.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:listByZone }
  requirements:
    _format: json|csv|html
  options:
    expose: true

wikipedale_report_list_by_bbox:
  pattern: /report/list/bybbox.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:listByBBox }
  requirements:
    _format: json|csv|html
  options:
    expose: true

wikipedale_report_change:
  pattern: /report/change.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:change }
  requirements:
    _format: json
  options:
    expose: true

wikipedale_report_designate_moderator:
  pattern: /report/designate/moderator.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:getDesignatedModerator }
  requirements:
    _format: json
  options:
    expose: true

wikipedale_user_confirm:
  pattern: /user/confirm/{token}/{reportId}.html
  defaults: {_controller: ProgracqteurWikipedaleBundle:Report:confirmUser }
  options:
    expose: true

wikipedale_photo_list_by_report:
  pattern: /photo/list/byreport/{reportId}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:getPhotoByReport }
  requirements:
    _format: json|html
  options:
    expose: true

wikipedale_photo_new:
  pattern: /photo/new/report-{reportId}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:new }
  requirements:
    _format: html
  options:
    expose: true

wikipedale_photo_view:
  pattern: /photo/view/{fileNameP}.{photoType}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:view }
  requirements:
    _format: html
  options:
    expose: true

wikipedale_photo_update:
  pattern: /photo/update/{fileNameP}.{photoType}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Photo:update }
  requirements:
    _format: html
  options:
    expose: true

wikipedale_authenticate:
  pattern: /authenticate.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Manager:httpBasicAuthenticate }
  requirements:
    _format: json
  options:
    expose: true

wikipedale_token_request_new:
  pattern: /token/new.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Token:getNewTokens}
  requirements:
    _format: json
  options:
    expose: true

wikipedale_history_report_by_zone:
  pattern: /history/reports/bycity/{citySlugP}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:ReportTracking:byCity }
  requirements:
    _format: json|atom
  options:
    expose: true

wikipedale_groups_list:
  pattern: /admin/group
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:list }
  options:
    expose: false

wikipedale_groups_create:
  pattern: /admin/group/create
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:create }
  options:
    expose: false

wikipedale_groups_update:
  pattern: /admin/group/update/{id}
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:update }
  options:
    expose: false

wikipedale_admin_user_show_form:
  pattern: /admin/user/show/{id}
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:userShowForm}
  options:
    expose: false

wikipedale_admin_user_new_virtual:
  pattern: /admin/user/virtual/new
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:newVirtualUser}
  options:
    expose: false

wikipedale_admin_user_create_virtual:
  pattern: /admin/user/virtual/create
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:createVirtualUser }
  options:
    expose: false

wikipedale_admin_homepage:
  pattern: /admin
  defaults: {_controller: ProgracqteurWikipedaleBundle:Admin:index }

wikipedale_admin_usergroups:
  pattern: /admin/usergroup
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:userList }

wikipedale_admin_usergroups_update:
  pattern: /admin/usergroup/user/{id}
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:userUpdate }

wikipedale_admin_usergroups_add_or_remove_groups:
  pattern: /admin/usergroup/user/{id}/add_remove_groups
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupAdmin:addRemoveGroups }
  requirements:
    method: POST

wikipedale_notification_subscriptions_list:
  pattern: /profile/notifications
  defaults:
    _controller: ProgracqteurWikipedaleBundle:Notifications:index 

wikipedale_notification_subscriptions_show:
  pattern: /profile/notifications/{id}
  defaults: 
    _controller: ProgracqteurWikipedaleBundle:Notifications:show

wikipedale_notification_subscriptions_update:
  pattern: /profile/notifications/{id}/update
  defaults:
    _controller: ProgracqteurWikipedaleBundle:Notifications:update

wikipedale_group_covers_zone:
  pattern: /groups/bytype/bycovering/{type}.{slugZone}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupFrontend:getGroupCoveringZone }
  requirements:
    _format: json
    method: GET
  options:
    expose: true

wikipedale_group_moderator_list:
  pattern: /groups/bytype/{type}.{_format}
  defaults: {_controller: ProgracqteurWikipedaleBundle:GroupFrontend:listByType }
  requirements:
    method: GET
  options:
    expose: true

wikipedale_zone_minisite:
  pattern: /{zoneSlug}
  defaults: {_controller: ProgracqteurWikipedaleBundle:Zone:selectZoneForMinisite }
  options:
    expose: true
