services:
    security.authentication.factory.wsse:
        class:  Progracqteur\WikipedaleBundle\Resources\Security\Authentication\WsseFactory
        tags:
            - { name: security.listener.factory }