parameters:
#    progracqteur_wikipedale.example.class: Progracqteur\WikipedaleBundle\Example

services:
#    progracqteur_wikipedale.example:
#        class: %progracqteur_wikipedale.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
