parameters:
#    progracqteur_wikipedale.example.class: Progracqteur\WikipedaleBundle\Example
  progracqteur_wikipedale.normalizer.class : Progracqteur\WikipedaleBundle\Resources\Normalizer\NormalizerSerializerService
  progracqteur_wikipedale.security.controlList.class : Progracqteur\WikipedaleBundle\Resources\Security\ChangeService
  progracqteur_wikipedale.service.photo.class: Progracqteur\WikipedaleBundle\Resources\Services\PhotoService
services:
  progracqteurWikipedaleSerializer:
    class: %progracqteur_wikipedale.normalizer.class%
    arguments:
      - "@service_container"
#    arguments: 
#      em: '@doctrine.orm.entity_manager'
#      securityContext: '@security.context'
  progracqteurWikipedaleSecurityControl:
    class: %progracqteur_wikipedale.security.controlList.class%
    arguments: 
      securityContext: '@security.context'
  progracqteurWikipedalePhotoService:
    class: %progracqteur_wikipedale.service.photo.class%
  progracqteurWikipedale.form.type.photo:
      class: Progracqteur\WikipedaleBundle\Form\Model\PhotoType
      arguments: ["@service_container"]
      tags:
          - { name: form.type, alias: photo }
          
  wsse.security.authentication.provider:
    class:  Progracqteur\WikipedaleBundle\Resources\Security\Authentication\WsseProvider
    arguments: ['', %kernel.cache_dir%/security/nonces]

  wsse.security.authentication.listener:
    class: Progracqteur\WikipedaleBundle\Resources\Security\Firewall\WsseListener
    arguments: ['@security.context', '@security.authentication.manager']  


    
#    progracqteur_wikipedale.example:
#        class: %progracqteur_wikipedale.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
