parameters:
#    progracqteur_wikipedale.example.class: Progracqteur\WikipedaleBundle\Example
  progracqteur_wikipedale.normalizer.class : Progracqteur\WikipedaleBundle\Resources\Normalizer\NormalizerSerializerService

services:
  progracqteurWikipedaleSerializer:
    class: %progracqteur_wikipedale.normalizer.class%
    arguments: 
      em: '@doctrine.orm.entity_manager'

#    progracqteur_wikipedale.example:
#        class: %progracqteur_wikipedale.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
