Progracqteur\WikipedaleBundle\Entity\Model\Place:
  getters:
    creator: 
      - NotNull: {message: La creator ne peut être nulle}
      - Type:
          type: object
          message: Le créateur doit être un objet
  properties:
    description:
      - MaxLength: {limit: 10000, message: La description ne peut pas être plus longue que 1000 caractères}
    geom:
      - NotNull: {message: Indiquez un emplacement géographique}
    statusBicycle:
      - Type:
          type: integer
          message: La valeur {{value}} n'est pas un type valide {{type}}
      - Min: {limit: 0, message: statusBicycle doit être supérieur à 0}
      - Max: {limit: 2, message: statusBicycle doit être inférieur à 2}
      - Max: {limit: 0, message: statusBicycle doit être égal à 0 lors de la création, groups: [creation]}
    statusCity:
      - Type:
          type: integer
          message: La valeur {{value}} n'est pas un type valide {{type}}
      - Min: {limit: 0, message: statusBicycle doit être supérieur à 0}
      - Max: {limit: 2, message: statusBicycle doit être inférieur à 2}
      - Max: {limit: 0, message: statusBicycle doit être égal à 0 lors de la création, groups: [creation]}
      