Progracqteur\WikipedaleBundle\Entity\Model\Place:
  getters:
    creator: 
      - NotNull: {message: La creator ne peut être nulle}
      - Type:
          type: object
          message: Le créateur doit être un objet
  properties:
    description:
      - MaxLength: {limit: 10000, message: La description ne peut pas être plus longue que 1000 caractères}
    geom:
      - NotNull: {message: Indiquez un emplacement géographique}
  constraints:
    - Callback:
        methods: [isStatusesValid, hasOnlyOneChange]

Progracqteur\WikipedaleBundle\Entity\Model\Photo:
  getters:
    fileObject:
      - Image:
          maxSize: 3096k
          maxSizeMessage: Le fichier est trop volumineux. Réduisez-le avant envoi.
          mimeTypes: [image/jpeg]
          mimeTypesMessage: Le fichier n'est pas un format accepté. Seul le format jpg est accepté.
    creator:
      - NotNull: {message: Le créateur ne peut pas être null}
    place:
      - NotNull: {message: La photo doit être reliée à un emplacement}
  properties:
    legend:
      - MaxLength: {limit: 500, message: La légende ne peut dépasser 500 caractères }
      
Progracqteur\WikipedaleBundle\Entity\Management\Notation:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: id
        message: admin.notation.id.not.unique
  properties:
    id: 
      - Regex:
          pattern: "/^[a-z0-9]/"
          message: admin.notation.id.must_be_character_alphabeticals_or_numeric
      - MaxLength: 20
      - MinLength: 3
    name:
      - NotBlank: ~
      - MaxLength: 60
      - MinLength: 3

Progracqteur\WikipedaleBundle\Entity\Management\Group:
  properties:
    name:
      - NotBlank: ~
      - MinLength: 5
      - MaxLength: 120