Progracqteur\WikipedaleBundle\Entity\Model\Place:
  getters:
    creator: 
      - NotNull: {message: Le créateur ne peut être nul}
      - Type:
        type: object
        message: Le créateur doit être un objet
  properties:
    description:
      - NotNull: {message: La description ne peut être nulle}
      - MaxLength: {limit: 10000, message: La description ne peut pas être plus longue que 1000 caractères}
    geom:
      - NotNull: {message: Indiquez un emplacement géographique}
    statusBicycle:
      - Type:
        type: integer
        message: La valeur {{value}} n'est pas un type valide {{type}}
      - Min: {limit: 0, message: statusBicycle doit être supérieur à 0}
      - Max: {limit: 2, message: statusBicycle doit être inférieur à 2}
    statusCity:
      - Type:
        type: integer
        message: La valeur {{value}} n'est pas un type valide {{type}}
      - Min: {limit: 0, message: statusBicycle doit être supérieur à 0}
      - Max: {limit: 2, message: statusBicycle doit être inférieur à 2}
      