Progracqteur\WikipedaleBundle\Entity\Management\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    creationDate: 
      type: datetime
    infos: 
      type: hash
    nbComment: 
      type: integer
    nbVote: 
      type: integer 