Progracqteur\WikipedaleBundle\Entity\Management\Notification\PendingNotification:
  type: entity
  readOnly: ~
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    subscription:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\NotificationSubscription
      mappedBy: pendingNotifications
      fetch: EAGER
    placeTracking:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place\PlaceTracking
      mappedBy: pendingNotifications
      fetch: EAGER