Progracqteur\WikipedaleBundle\Entity\Management\Notification\PendingNotification:
  type: entity
  readOnly: ~
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    subscription:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\NotificationSubscription
      mappedBy: pendingNotifications
      fetch: EAGER
    reportTracking:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Report\ReportTracking
      mappedBy: pendingNotifications
      fetch: EAGER
      joinColumn:
        name: placetracking_id
        referencedColumnName: id