Progracqteur\WikipedaleBundle\Entity\Management\Group:
  type: entity
  table: group_table
  repositoryClass: Progracqteur\WikipedaleBundle\EntityRepositories\Management\GroupRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    type:
      type: string
      column: gtype
      length: 12
  manyToOne:
    notation:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Notation
      nullable: true
    zone:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Zone
      nullable: true