Progracqteur\WikipedaleBundle\Entity\Management\NotificationSubscription:
  type: entity
  table: notification_subscription
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    kind:
      type: string
      length: 20
    frequency:
      type: integer
    transporter:
      type: string
      length: 20
  manyToOne:
    zone:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Zone
      inversedBy: notificationSubscriptions
      nullable: true
    owner:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
      inversedBy: notificationSubscriptions
      cascade: [persist]
    group:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Group
      inversedBy: notificationSubscriptions
      nullable: true
    groupRef:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Group
      inversedBy: notificationSubscriptions
      nullable: true
    report:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Report
      inversedBy: notificationSubscriptions
      nullable: true
      joinColumn:
        name: place_id
        referencedColumnName: id