Progracqteur\WikipedaleBundle\Entity\Model\Photo:
  type: entity
  table: photos
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  indexes:
    photo_file:
      columns: [file]
  fields:
    file:
      type: string
      length: 255
    height:
      type: integer
    width:
      type: integer
    createDate:
      type: datetime
    legend:
      type: string
      length: 500
    published:
      type: boolean
  manyToOne:
    creator:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
    place:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place
      inversedBy: photos
  lifecycleCallbacks:
    prePersist: [ preUpload, informPlace ]
    preUpdate: [ preUpload, informPlace ]
    postPersist: [ upload ]
    postUpdate: [ upload ]