Progracqteur\WikipedaleBundle\Entity\Model\Comment:
  type: entity
  table: comments
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  indexes:
    filter_type:
      columns: [kind]
  fields:
    content:
      type: text
    published:
      type: boolean
    creationDate:
      type: datetime
    updateDate:
      type: datetime
    type:
      type: string
      length: 10
      column: kind
  manyToOne:
    creator:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
      mappedBy: comments
    report:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Report
      mappedBy: comments
      cascade: [persist]
      joinColumn:
        name: place_id
        referencedColumnName: id
  lifecycleCallbacks:
    preFlush: [registerToReport]
