## YAML Template.
---
Progracqteur\WikipedaleBundle\Entity\Model\Place\PlaceTracking:
  type: entity
  repositoryClass: Progracqteur\WikipedaleBundle\EntityRepositories\Model\Place\PlaceTrackingRepository
  readOnly: ~
  table: placeTracking
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    isCreation:
      type: boolean
      nullable: true
    details:
      type: hash
    date:
      type: datetime
  lifecycleCallbacks:
    #checkIfEmpty seems to be not efficient
    prePersist: [checkIfEmpty]
  manyToOne:
    author:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
      nullable: true
      mappedBy: PlaceChanges
    place:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place
      inversedBy: changesets
