## YAML Template.
---
Progracqteur\WikipedaleBundle\Entity\Model\Place:
  changeTrackingPolicy: NOTIFY
#FIXME: implémenter le tracking policy: pour l'instant, rien ne change
  type: entity
  table: place
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    geom:
      type: point
    description:
      type: text
    createDate:
      type: datetime
    nbVote:
      type: integer
    nbComm:
      type: integer
    infos:
      type: hash
    nbPhoto:
      type: integer
    address:
      type: address
    lastUpdate:
      type: datetime
    accepted:
      type: boolean
      default: true
  manyToOne:
#    category:
#      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Category
#      nullable: true
    creator:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
      nullable: true
      mappedBy: places
    manager:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Group
      nullable: true
      mappedBy: place
    type:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place\PlaceType
      nullable: true
      mappedBy: places
  oneToMany:
    photos:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Photo
      mappedBy: place
    changesets:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place\PlaceTracking
      mappedBy: place
      cascade: [persist]
  manyToMany:
    category:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Category
      nullable: true
