Progracqteur\WikipedaleBundle\Entity\Model\Comment:
  type: entity
  table: comments
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    content:
      type: string
    published:
      type: boolean
    creationDate:
      type: datetime
    updateDate:
      type: datetime
    type:
      type: string
      length: 10
      column: kind
  manyToOne:
    creator:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\User
      mappedBy: comments
    place:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Place
      mappedBy: comments
      cascade: [persist]